---
title: "Chapter 7: Analysis of one-way and two-way tables"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: true
    smooth_scroll: true
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In Chapter 7 of the textbook **Practical Methods for Design and Analysis of Complex Surveys**, testing procedures for one-way and two-way tables are presented. The test statistics include a design-based Wald test statistic and various Rao-Scott adjusted test statistics. These test statistics are constructed to account for the sampling complexities, such as stratification, clustering and weighting, thus providing asymptotically valid testing procedures for complex surveys.

In **Training Key 250,** a design-based Wald test statistic of independence hypothesis for a two-way table is calculated and compared with an unadjusted Pearson test statistic, thus reproducing the results of Example 7.3. The Occupational Health Care Survey data set is used.

NOTE: Instructions for the use of Training Keys are given in the Instructions section.


# TRAINING KEY 250: Test of Independence

### INTRODUCTION

Example 7.3. In this Training Key we will study whether the variables PHYS (physical health hazards of work: None or Some) and PSYCH3 (overall psychic strain classified into three nearly equally sized classes) are associated or not. We use [OHC Survey data](concepts/concepts.html) as an example data set. The general purpose is to show how the sampling design affects to the test of independence of two categorical variables.


#### A) TEST OF INDEPENDENCE

We will demonstrate how to carry out the test of independence of health hazards of work and psychic strain in the OHC Survey setting. Further instructions are given once you start.
 
<a href="Keys/key250/key250_9.htm" target="_blank">SAS version 9</a>  

NOTE: Due to the simplicity of the problem, we do not include the interactive analysis option in this training key.

